### ISSUE TITLE
Using rails autocomplete for text field, NOT form submission?

### ISSUE THREAD

**Issue by onebree** [bigtunacan/rails-jquery-autocomplete#13]
I am constructing a page similar to jquery nested forms. It will be a table where you can click-to-add a telephone number. Upon adding a row, you will see a blank text field and a delete button.

My goal is to use Rails Autocomplete since it works with ActiveRecord. If the user has 100 telephone numbers, I would like them to search for text. Upon clicking the list item, the text field will contain the telephone number. When the form submits, it will be seen as a nested attribute, where the text entered matches a phone number's tn (not id).

From looking at the sample apps, it seems that this gem's main functionality is for searching, and redirecting to a new path. I do not want to redirect to a new path, but simply want to use ActiveRecord entries to populate the autocomplete drop down.

I read the [source](http://jqueryui.com/autocomplete/) on jQuery UI's site, but it provides a static array of items to choose from within the Javascript.

**Comment by bigtunacan** [comment]
@onebree Is the `autocomplete_field_tag` helper what you are looking for?  It is documented on the README.

**Comment by onebree** [comment]
I thought about that at first. This is what the form will look like (still working on it). Disregard the bootstrap form stuff, as that is simply for styling, and does not affect functionality.

```haml
// index.html.haml
= bootstrap_nested_form_for(@location, url: "/telephone_numbers/update") do |f|
  .section
    %table.data#numbers_target
      %thead
        %tr
          %th Number
          %th Delete
      %tbody
        = f.fields_for :telephone_numbers, wrapper: false
    .center=f.link_to_add "Add Number", :telephone_numbers, class: :button, data: {target: "#numbers_target"}
    .center= f.submit "Update", class: "btn btn-success"

// _telephone_number_fields.html.haml
%tr.fields
  %td
    // Autocomplete telephone number here
  %td= f.link_to_remove fa_icon("remove 2x")                                                    
```

**Comment by onebree** [comment]
@bigtunacan I figure out that just because it leads to an autocomplete route, it does not mean the form has to go to such route. (It is for the autocomplete function only). I am going to close the issue.
