### ISSUE TITLE
If a form fails, how do I retain the autocompleted field's input?

### ISSUE THREAD

**Issue by onebree** [bigtunacan/rails-jquery-autocomplete#16]
I have a nested form, where I add telephone numbers to a location. If any errors are present, the index is rendered. The nested fields are still present, but the contents of each field is gone. How do I retain the contents if the form fails?

I am using `nested_forms` gem, rendering the `fields_for` in a partial.

**Comment by bigtunacan** [comment]
@onebree Trying to get caught back up again; were you able to resolve this issue?

**Comment by onebree** [comment]
No I was not. IDK if it is because of the nested forms gem. Do you need additional info?

**Comment by bigtunacan** [comment]
@onebree Trying to get caught up here again.  If you are still having issues I will need more info for this.  If you could replicate the issue with a basic repo that would be ideal.

**Comment by onebree** [comment]
@bigtunacan Hello. I have not looked into the issue further, as I finished the project I was working on at the time. I am going to close this issue, until (if) it happens again.
