### ISSUE TITLE
bundle update doesn't provide latest version?

### ISSUE THREAD

**Issue by eiked** [bigtunacan/rails-jquery-autocomplete#18]
First of all, big thanks for now taking care of this very valuable gem.

Please correct me if I'm wrong. I don't know how this actually works with the gems ...

It seems if I put in my Gemfile:
   gem 'rails-jquery-autocomplete'
and do
  bundle update rails-jquery-autocomplete'

I't looks for me that I do not get the current version. Is this still marked as rc or something?

You might want to bump the version number and make the current version the official one,
because there are a lot of very useful fixes in there.

The fix for simple_form was absolutely valuable as was the recent change for triggering the change event

**Comment by bigtunacan** [comment]
@eiked If you just specify `gem 'rails-jquery-autocomplete` in your Gemfile then the bundle update would get the latest version of the released gem on whatever gem repo your Gemfile points to `source 'http://rubygems.org'` by default.

This would be version 1.0.1 as seen on rubygems here https://rubygems.org/gems/rails-jquery-autocomplete.

That does not yet include the latest changes such as the fix for simple_form.  If you need something that has not been released yet you can point directly to the git branch using something like this in your Gemfile

`gem 'rails-jquery-autocomplete', :git => 'https://github.com/bigtunacan/rails-jquery-autocomplete', :branch => :master`

Otherwise I will be deploying a new release in about 2 weeks when I am in between classes.

**Comment by eiked** [comment]
Hi bigtunacan,

Thanks for your reply.

I was not aware of this :branch => :master thing,
Learning every day …

I hope you do like the solution in #19.
You might want to add that to the examples.

I;d like to suggest to make that part of the api.
aka ‘data-autocomplete-submit: true’ should trigger that behaviour.

Nice to meet you
~eike

I should add some more ideas on
https://github.com/bigtunacan/rails-jquery-autocomplete/issues/20 <https://github.com/bigtunacan/rails-jquery-autocomplete/issues/20>


And fished this (it was not in bsd4.1c)
http://minnie.tuhs.org/cgi-bin/utree.pl?file=4.2BSD/usr/man/man8/tunefs.8 <http://minnie.tuhs.org/cgi-bin/utree.pl?file=4.2BSD/usr/man/man8/tunefs.8>

    You can tune a file system, but you can't tune a fish.
hope you like that one.
~eike

**Comment by eiked** [comment]
https://github.com/bigtunacan/rails-jquery-autocomplete/issues/20 <https://github.com/bigtunacan/rails-jquery-autocomplete/issues/20>

First of all, big thanks again for taking care of the autocomplete gem.

This is something that we really need every day, everywhere.

I believe there is room to improve.

Let us first dissect that.
It quite does have some layers.


Bottom up:
- how it is routed (not yet handeled?), needs a convention
- easily building a query against the model
- augmenting the query with additional data (could be improved)
- responding (with json nowdays)

- receiving the response in the browser
- handling the repsonse in the browser
- adopting to jquery-ui/autocomplete

- integration with other gems (I use simple form)

- sending the request fields back to the server

-----------

The jquery-ui autocomplete gives a lot of service,
but it also is a lot of drag.

I did cope with adaptor javascript a lot, that;s not fun ...
you know what I mean.
This is all very complicated stuff, heavily involved with the intricacies of the jquery-ui

I did want to add an icon in front, maybe some pretty layout for the list,
and this made me getting even deeper into that jquery stuff.

It’s not much fun to make html layouts with Javascript.

Currently the autocomplete is based on sending json from the server to the client.
But I’d (alternatively) like to send HTML, rendered by using haml, erb whatever.

I’m thinking of getting rid of the jquery-ui-autocomplete  dependency altogether.
And to come up instead with some very slim js code, to do the same functionality.

I believe that the list should not be rendered on the client, but be rendered on the server.
So we would ship the list as HTML (not json)
This would enable us, to use all tricks on the srver side,
to render a very beautiful list.


I know this is divergent from the idea of integrating jquery-ui-autocomplete,
it is much about throwing jquery out.

But I hope you got the idea.

We currently have the gem montaged at
https://www.rockers.de/en <https://www.rockers.de/en>


(and in a lot of places in the backend)

Regards,
~eike
