### ISSUE TITLE
Triggering the change event does not submit automatically

### ISSUE THREAD

**Issue by eiked** [bigtunacan/rails-jquery-autocomplete#19]
Thanks for triggering the change event.

But this did not autosubmit the form for me.
It probably should not? But just trigger the change event?
Maybe I was doing something wrong.
Otherwise adding an configurable autosubmit facility might make a lot of sense for a lot of use cases.

I reverted back to the soution that I used with the old rails3-autocomplete.
I use this bit of coffee which makes this work for me
(need to give the input field the class 'autocomplete_submit', probably data-autosubmit would be even  better ...)

```coffescript
#
#   submit autocomplete on select
#   drop this into assets/javascript/autocomplete_submit.coffee
#
$ ->
    $('.autocomplete_submit')
        .bind 'railsAutocomplete.select',
                (event, data) ->
                    $(this).closest('form').submit()

```

**Comment by bigtunacan** [comment]
@eiked I think what you have done is a good way to handle this by extending it to do the auto submit.  In many cases users want to autocomplete, but not submit the form as there will be fields that still need filled in, reviewed, etc... prior to submission.  Consider as a simple case of autocompleting shipping information for an existing customer.  This is convenient, but they will need to update the address before submission if they have moved.
