### ISSUE TITLE
not selecting unique values with scope

### ISSUE THREAD

**Issue by turbochef** [bigtunacan/rails-jquery-autocomplete#22]
I have 2 search boxes in a form where the first one returns the customer name and the second should return the all the customers' companies.

Everything seems to work okay except if 2 customers have the same company in the database, the company autocomplete field returns the same company twice.

I tried setting the scope in the controller like this:

    autocomplete  :customer, :name, full:true
    autocomplete  :customer, :company, full:true, scopes:[:compscope]

And here is the scope:

    scope :compscope, -> {Customer.select("DISTINCT company")}

Here is the view (in slim)

    
      .field
        = f.label :company 
        br
        = f.autocomplete_field :company, :autocomplete_customer_company

Could you help me fix it so the field returns unique results?

![image](https://cloud.githubusercontent.com/assets/10778363/9040371/4ccba6cc-39c7-11e5-9377-fd08461b6097.png)

**Comment by bigtunacan** [comment]
@turbochef, are you still having this issue? Have you tested your scope outside of autocomplete to see if you are getting duplicates?  Are you able to duplicate the problem in a public repo that I can test?

**Comment by turbochef** [comment]
Thank you for following up. I have back to back meetings until 1:00 pm CST but I'll try to get you something asap.

**Comment by turbochef** [comment]
The scope seems to work well, here's the screenshot of the controller and result

![image](https://cloud.githubusercontent.com/assets/10778363/9360055/ac70b42a-4659-11e5-98e7-32739b486d9c.png)

**Comment by turbochef** [comment]
I'm currently at work which doesn't allow me to push to github.  If you still need it later I'll try to make it after work.

**Comment by bigtunacan** [comment]
@turbochef Just push it when you are able to and I'll take a look; I don't see enough here to notice anything that should be causing an issue.  No rush anyway; It may be a couple of days before I can get back to it.

**Comment by bigtunacan** [comment]
@turbochef Closing since it has been a couple of months without a follow up.  If you are still having issues, please provide additional information and we can re-open.

Thanks.
