### ISSUE TITLE
String -> Boolean casting on 'showNoMatches' options

### ISSUE THREAD

**Issue by ryanmcilmoyl** [bigtunacan/rails-jquery-autocomplete#25]
When checking for showNoMatches, you're currently doing a boolean check.  However, if you get the value from the form element's 'data-showNoMatches' attribute, you will get a string.  In javascript, the string "false" will evaluate to true.

You either need to special case the retrieval of boolean values from data-attributes and do some sort of string -> boolean conversion 

```
if (value === 'false') {
  value = false
}
```
Or, do a string check when testing the value

```
if (option && option !== 'false') {
  // do some stuff here
}
```

**Comment by bigtunacan** [comment]
@ryanmcilmoyl Thanks; this should be fixed on the 1.0.2 version of the gem that I just released.
