### ISSUE TITLE
Generated action?

### ISSUE THREAD

**Issue by BeeZerk** [bigtunacan/rails-jquery-autocomplete#26]
"This will create an action autocomplete_brand_name on your controller, don't forget to add it on your routes file"

This never happens. I always get an exception that the action is not there.

**Comment by bigtunacan** [comment]
@BeeZerk Can you provide more information.  Duplicate it with a basic project on a git repo or something?  There is too little information here to go on.

**Comment by bigtunacan** [comment]
@BeeZerk closing since there has been no further contact.  If you are still having issues please provide additional information and we can re-open.
