### ISSUE TITLE
undefined method `brand_name' for #<Product:0x007f976845dab0>

### ISSUE THREAD

**Issue by kinders** [bigtunacan/rails-jquery-autocomplete#3]
hi, i'm a newer

<strong>here is the Gemfile</strong>

gem 'rails', '4.2.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'rails-jquery-autocomplete'

<strong> i think i had followed the step </strong>
1. $ bundle install
2. $rails g autocomplete:install
create  public/javascripts/autocomplete-rails.js
3. in app/views/layouts/application.html.erb, i had added:
    <%= javascript_include_tag "autocomplete-rails.js" %>
4. in app/asserts/javascripts/application.js，i'd added:
    //= require jquery
    //= require jquery_ujs
    //= require jquery-ui
    //= require autocomplete-rails
5. i do nothing in model, and change the controller, routes, view codes as README。

6. i  rake routes, the `autocomplete_brand_name_products_path` is ok

that all.

<strong>am i missing something important? </strong> 

thank you!

**Comment by Kledal** [comment]
Did you find a solution on your problem? I seem to have the same problem as of now..

**Comment by bigtunacan** [comment]
@kinders it appears you have the order of the class name and method name specified in the wrong order.

The route `autocomplete_brand_name_products_path` indicates a class/model of BrandName and method called Products.  I assume you have a Products model that you are looking up the brand name.

This would be specified as follows.

In your controller.

`autocomplete :products, :brand_name`

In your routes.

`autocomplete_products_brand_name`

**Comment by kinders** [comment]
@bigtunacan , thank you for your help!
after one month, i check my old codes today, and i find something wrong in the products_controller.rb:

      autocomplete :brand, :id, full: true, extra_data: [:name]

now i rewrite this line, so this bug is fixed.

i'm so sorry to waste your time!
