### ISSUE TITLE
minLength ?

### ISSUE THREAD

**Issue by austinarchibald** [bigtunacan/rails-jquery-autocomplete#30]
Any way to adjust how many characters are required before it performs a search? [minLength](https://api.jqueryui.com/autocomplete/#option-minLength) is defaulted to 1, but 2 characters are required to search when I implement the gem. I tried `'data-min-length' => 1` to try and force it, but to no avail. Thanks.

**Comment by bigtunacan** [comment]
@austinarchibald This is a bit unintuitive since we are using data attributes for most things, but minLength is not prefixed this way; so you should use just `'min-length' => 1`.

I'm going to mark this as a bug  and in the next release I'll add support for both to maintain consistency while not breaking backwards compatibility.

**Comment by austinarchibald** [comment]
Fantastic. Worked great. Completely unrelated, but maybe you have some tips on how to approach solving it... for the life of me I cannot get CSS to override the defaults. I've tried the [`foods.scss`](https://github.com/yifeiwu/rails4-autocomplete-demo/blob/master/app/assets/stylesheets/foods.scss) and some [other](https://gist.github.com/paseto/5b0f626bbf4ccdcc0b09) ideas. The only thing that seems to make any change is related to the width of the results box. Vexing. But perhaps too hard for you to say without seeing my code...

Thanks again!

**Comment by bigtunacan** [comment]
@austinarchibald Difficult to say without seeing your code.  My first guess would be the order that the styles are being applied is not swapped since the last style set wins in CSS.

**Comment by bigtunacan** [comment]
Fixed in master. Will ship in next release.
