### ISSUE TITLE
Having trouble using gem with Rails 4.1.1 app

### ISSUE THREAD

**Issue by onebree** [bigtunacan/rails-jquery-autocomplete#32]
We already use this gem for a Rails 4.2.0 app. I wanted to implement it for this other app, Rails 4.1.1, but I am having issues. I ran `bundle install` along with `rails g ...` to store the javascript file in `public/javascripts`. I have even restarted the app with no success.

```ruby
gem 'rails', '4.1.1'
gem 'rails-jquery-autocomplete'
gem 'jquery-rails'
```

```js
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require jquery-ui/autocomplete
//= require autocomplete-rails
//= require_tree .
//= require jquery_nested_form
//= require bootstrap
//= require turbolinks
```

Here is my error message:

```
Showing /home/hstevens/contract_app/app/views/layouts/application.html.haml where line #6 raised:

couldn't find file 'jquery-ui/autocomplete'
  (in /home/hstevens/contract_app/app/assets/javascripts/application.js:16)

3    %head
4      %title Contract Application
5      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
6      = javascript_include_tag 'application', 'data-turbolinks-track' => true
7      = javascript_include_tag 'autocomplete-rails.js'
8      = csrf_meta_tags
9    %body
```

**Comment by mauriciopasquier** [comment]
Check if you're depending on an old version of [jquery-ui](https://github.com/joliss/jquery-ui-rails/blob/master/History.md#500), some time ago it was loaded with `jquery.ui`

**Comment by onebree** [comment]
@mauriciopasquier the project that experienced the issue is using: `jquery-rails (3.1.0)`

**Comment by mauriciopasquier** [comment]
From `jquery-rails` [docs](https://github.com/rails/jquery-rails#installation):

    For jQuery UI, we recommend the jquery-ui-rails gem, as it includes the jquery-ui css and allows easier customization.

    As of v3.0, jquery-rails no longer includes jQuery UI. Use the jquery-ui-rails gem above.

You have to include it in your Gemfile, I don't think this gem depends on it.

**Comment by onebree** [comment]
@mauriciopasquier I will look into this further on Friday. Thank you for researching!

**Comment by onebree** [comment]
@mauriciopasquier Thank you for the advice. I added the gem `jquery-ui-rails` and everything seems to work now. No need to run `rails g` either!

**Comment by mauriciopasquier** [comment]
No problem!

**Comment by onebree** [comment]
Just as a quick aside, I do not want to use this gem to search. Rather, instead of a select box filled with 100 companies to choose from, I want to use this gem to allow the end user to type for a company name. This value would then be saved to the model.

When I try to do this, the field does not autocomplete in the form. Any advice?
