### ISSUE TITLE
Minified Javascript is out of date

### ISSUE THREAD

**Issue by WendyBeth** [bigtunacan/rails-jquery-autocomplete#36]
https://github.com/peterwillcn/rails4-autocomplete/issues/22

**Comment by bigtunacan** [comment]
@WendyBeth Are you still using the rails4-autocomplete gem or have you updated to rails-jquery-autocomplete?  I don't think this is an issue here.  Can you confirm?

**Comment by bigtunacan** [comment]
@WendyBeth Since I haven't heard anything back on this I'm going to assume that this was only an issue on the outdated repo.  If you are still having issues let me know.
