### ISSUE TITLE
Can you include the sample app for rails 4?

### ISSUE THREAD

**Issue by yifeiwu** [bigtunacan/rails-jquery-autocomplete#4]

**Comment by yifeiwu** [comment]
Nvm, I got this working. I'll upload an example repository soon

**Comment by yifeiwu** [comment]
https://github.com/yifeiwu/rails4-autocomplete-demo

**Comment by onebree** [comment]
@yifeiwu you should submit a PR that edits the README to include your demo app, rather than letting this issue sit as open.

**Comment by yifeiwu** [comment]
I will once I figure out how to do that lol. I'm pretty new at contributing to open source.

**Comment by thepoppingone** [comment]
@yifeiwu thanks for your demo! You can help by indicating the css classes in the README for styling the autocomplete boxes!

**Comment by bigtunacan** [comment]
Looks like I forgot to close this after adding it to the documentation previously.
