### ISSUE TITLE
Custom message when not results are found

### ISSUE THREAD

**Issue by mosinski** [bigtunacan/rails-jquery-autocomplete#46]
Hi,
I'm trying to translate the message but even on this simple example below does not work...
Still I get the message 'no existing match'
Does anyone know why :question: 
```
<%= f.autocomplete_field :location_id, autocomplete_location_name_trainings_path, :"data-autocomplete-label" => "Sorry, nothing found.", update_elements: {}, class: 'form-control' %>
#or
 <%= f.autocomplete_field :location_id, autocomplete_location_name_trainings_path, 'data-noMatchesLabel' => "Sorry, nothing found.", update_elements: {}, class: 'form-control' %>
```

**Comment by bigtunacan** [comment]
@mosinski If you can set it globally for your application then the following is the easiest.

    jQuery.railsAutocomplete.options.noMatchesLabel = "Whatever Text You Want"

**Comment by bigtunacan** [comment]
@mosinski Seeing as I haven't heard anything back in about a month I will assume this is resolved.
