### ISSUE TITLE
Arrow keys up and down are not working

### ISSUE THREAD

**Issue by anasawad** [bigtunacan/rails-jquery-autocomplete#5]
I used the rails3-jquery-autocomplete gem with rails 3 application and arrows up and down was working fine, but when upgrading to rails 4 and using this gem, the arrows are no more working. Please provide us with solution if there are any conflicts with JS of the upgraded gem ?

**Comment by bigtunacan** [comment]
@anasawad I see you closed this.  Were you able to get it working?

**Comment by anasawad** [comment]
@bigtunacan , Yes, thanks for your concern :)

**Comment by cchandler81** [comment]
@anasawad What did you have to do to get this working? I can't seem to. Thanks.
