### ISSUE TITLE
autocomplete on search form works when logged in, 401 when not (help request)

### ISSUE THREAD

**Issue by bodaonline** [bigtunacan/rails-jquery-autocomplete#50]
Hi Folks,

can you help me out pls? This is probably not an issue with the code but with me being a beginner. 

Got the autocomplete working but it only works when I am logged on (devise). When I am not logged on no suggestion pops under and when I inspect the element  I see this in the Console tab I see:
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
https://xxxxxxxxxxxx.c9.io/assets/jquery.self-d03a5....f96ea7c074.js?body=1
```
and it points to this in the Sources tab
`xhr.send( ( options.hasContent && options.data ) || null );`

I googled this and found a few stackoverflow suggestions regarding this 
`<%= csrf_meta_tags %>`
in my application.html.erb but I didn't understand most :) and the rest didn't help. :(

TIA!

**Comment by bigtunacan** [comment]
What version of Rails are you using?

**Comment by bodaonline** [comment]
Hi its 4.2.5

**Comment by bigtunacan** [comment]
Ok, I do not personally use the devise gem for authentication, but took a quick look at their documentation.

Have you excluded the autocomplete action from requiring devise authentication?

Something like this should go in the controller where the action is defined.

`before_action :authenticate_user!, :except => [:action_to_exclude_from_authentication]`

Also, stay away from the `csrf` stuff unless you understand what you are doing and the security implications.  CSRF is cross site request forgery, without getting too technical this means your site can be accessed by a client that doesn't co-exist on your web server.  A good example would be a web service that needs to service a mobile application.  By default Rails (and any good web framework) disables this by default and you must enable it only if it is something you really need.

**Comment by bigtunacan** [comment]
Do you literally have `:autocomplete` in the :except array?  If so, that would not work; `:autocomplete` is not the controller action, it is a method that is used by the rails-jquery-autocomplete gem to generate an autocomplete action for your controller.

So in the Readme example I have the following

    class ProductsController < Admin::BaseController
      autocomplete :brand, :name
    end

This generates the action `: autocomplete_brand_name` which would be the action needing to be added to your except block.

**Comment by bodaonline** [comment]
Sorry, told you I am new to this. :) That was it, that fixed it (+restart server +browser cache emptying) Million thanks! Would send you a beer but obviously that would be against the law wherever you live ;)

**Comment by bigtunacan** [comment]
No worries.
