### ISSUE TITLE
Different autocompletes scopes

### ISSUE THREAD

**Issue by jeager** [bigtunacan/rails-jquery-autocomplete#54]
Hello!

I'm working on a application that needs some scopes, like User.friends(current_user.id) for the autocomplete. I was able to do that by overriding the get_autocomplete_items. But the problem is that I have two autocomplete paths for the same controller which I overrided the method: 

The autocomplete_user_name_users_path and the and the autocomplete_user_email_users_path. 

And now they both get "filtered" the same way because of the overriding of the autocomplete method. Is there a way to put another param beside the "term" param that goes to the method? than I could just put an if and be happy.. Or if there is another solution for this.

**Comment by jeager** [comment]
I found the answer.. It's actually pretty simple. If you send the parameter like this (autocomplete_user_name_users_path(:search_mode=>'name')), you can recover it in your get_autocomplete_items method and choose which way to filter the scopes.

I think you guys should add this section to the readme, it's pretty useful. Sorry for bothering!

**Comment by etcook** [comment]
@jeager Do you mind providing a bit more information on how you "receovered" the param in the method? I need to have access to different scopes as well, primarily for filtering.

**Comment by jeager** [comment]
hello @etcook , When you need different scopes,  you can send a param in the path, like this

`autocomplete_user_name_users_path(:search_mode=>'name')`

but to really filter, you need to put this method inside the controller

`def get_autocomplete_items (parameters)

    if(params[:search_mode].eql? 'name')
      items = User.where(User.arel_table[:name].matches("%#{params[:term]}%"))
    else
      items = active_record_get_autocomplete_items(parameters)
    end
  end`

and inside this method you can manipulate which itens will be send back to the view.

Hope it was helpful.

**Comment by etcook** [comment]
@jeager This is very helpful, thank you. So I'm assuming you're just overriding the default "get_autocomplete_items" behavior with your own to achieve this? There's no way to just feed in a separate scope for the end point, is that correct?

Thanks agains!

**Comment by jeager** [comment]
@etcook, if you just want to put scopes that doesnt need specific querys, you can just do like the gem 
sugests.
scopes

Added option to use scopes. Pass scopes in an array. e.g :scopes => [:scope1, :scope2]

if you add thia option in front of the autocomplete call inside the model, it should work :)

**Comment by etcook** [comment]
@jeager doesn't that just hardcode the scope? You pass the scopes in when instantiating the handler, but I can't seem to find a way to make that conditional, as you don't get route information when first creating the controller class. I just need to be able to select between a scope and unscoped query.  Sorry if I'm being dense and not seeing the obvious.

**Comment by jeager** [comment]
@etcook the example I gave does exactly that.

if(params[:search_mode].eql? 'name')

name is the search_mode, the other search mode is by email, that is the default, so I just return the autocomplete results, I hope you did understand!
