### ISSUE TITLE
How to make value/label different?

### ISSUE THREAD

**Issue by Streek** [bigtunacan/rails-jquery-autocomplete#59]
Assuming a json output of 

[{
  id: "2",
  label: "tram",
  value: "tram"
}]

How would I change it so that label = tram but value = 2,  I need to post the ID of the object not the name.

**Comment by yashwinkumar** [comment]
I too have the same question. We need to save `Id` of the object not the name of the object.
What do we need to do to make it working. I'm using simple form for.

**Comment by kakra** [comment]
Just use the helper I referenced or create your own autocompleter like I did:

    def render_autocompleter term, *indexes
      options = indexes.first.is_a?(Hash) ? indexes.shift : {}
      results = Searchkick.search(term, { fields: [autocomplete: :word_start], index_name: indexes, limit: 20, misspellings: { below: 5, edit_distance: 3 }}.merge(options))
      if block_given?
        render json: results.map {|r| yield r }.uniq {|r| r[:id] || r[:label] }
      else
        render json: results.map {|r| { id: dom_id(r), url: r.internal_url, value: r.common_title, label: r.common_path } }.uniq {|r| r[:id] }
      end
    end

This is used by me for returning elasticsearch results. I hope you get the idea, just put into value whatever you prefer. I call this method from autocomplete actions like so:

    def autocomplete_something
      render_autocompleter params[:term], Model1, Model2 do |result|
        { label: result.name, value: result.id }
      end
    end

Without a block, it renders a generic default json I'm using in multiple locations in the views.

This one is used to update multiple text fields at once from the autocompleter:

    def autocomplete_trip_destination
      options = current_editor.is_admin? ? {} : { where: { _id: current_editor.allowed_trips.pluck(:id) } }
      render_autocompleter params[:term], options.merge(fields: [autocomplete: :word_start]), Trip do |trip|
        autofill = autofill_data trip, :destination_category, :destination_location, :destination_country, :accommodation_key, :accommodation_text, :transport
        { id: trip.id, label: trip.destination, value: trip.destination }.merge autofill
      end
    end

    private

    def autofill_data object, *attributes
      attributes.inject({}) {|data,attribute| data.merge(attribute => object.send(attribute)) }
    end
