### ISSUE TITLE
Autocompletes hidden under modal

### ISSUE THREAD

**Issue by aussiDavid** [bigtunacan/rails-jquery-autocomplete#65]
When using the autocomplete field in a bootstrap modal the suggestions list is underneath the modal.

See screenshot for example.
![screen shot 2016-07-09 at 10 58 36 am 2](https://cloud.githubusercontent.com/assets/5856280/16705310/890e55b2-45c4-11e6-9c37-189a93bf3b52.png)

**Comment by bigtunacan** [comment]
@aussiDavid I would not expect this behavior and while I regularly use it with Bootstrap I don't recall using it with a modal.  Can you duplicate this in a minimal project and make it available to me?

**Comment by uditunpluged** [comment]
Same is happening with me.... the autocomplete is not working inside a modal but outside it works

**Comment by uditunpluged** [comment]
Solved ! It is a work around. Do the following

1. In your **application.js** add following line in your initialised jquery method:
`    $( "#IdOfAutoCompleteTextTag" ).autocomplete( "option", "appendTo", "#IdOfModal" );
`
2. In your respective **css.scss** file add the following:
```
.ui-front {
  z-index: 312321312312312 !important;
}
```
This is what we indians call it as JUGAAAD.
;) peace

**Comment by dmcwilliams** [comment]
For anyone else looking at this issue, the gem has been updated and defined at https://github.com/bigtunacan/rails-jquery-autocomplete/#changing-destination-element
