### ISSUE TITLE
Autocomplete is not a function error in browser console.

### ISSUE THREAD

**Issue by focampo92** [bigtunacan/rails-jquery-autocomplete#67]
This is my Application.js

//
//= require jquery
//= require jquery_ujs
//= require jquery-ui
//= require autocomplete-rails
//= require highcharts.js
//= require masonry.js
//= require moment
//= require bootstrap-datepicker
//= require bootstrap-datetimepicker
//= require chosen-jquery
//= require tinymce-jquery
//= require_tree .

my rails version 4.0.2. This happens only in production mode, in dev mode works well. Help me please, thanks.

**Comment by bigtunacan** [comment]
There is too little information here.
