### ISSUE TITLE
No idea how to use

### ISSUE THREAD

**Issue by black-snow** [bigtunacan/rails-jquery-autocomplete#90]
Is this project still maintained? Lots of old open issues.

I've read https://github.com/activeadmin/activeadmin/issues/1754 and a couple other posts but I still fail to integrate autocompletion with active admin.

I have a model `Event` and a model `Location` and `Event` has a `location_id`. I'd like to have an input field that autocompletes the `Location` by name. Can anyone guide me?

**Comment by seanabrahams** [comment]
@black-snow The issue is that the published gem does not have the latest code from this repo. Thus:
```ruby
gem 'rails-jquery-autocomplete'
```
does not work with jQuery3. You need to specify the repo:
```ruby
gem 'rails-jquery-autocomplete', github: 'bigtunacan/rails-jquery-autocomplete'
```
@bigtunacan it would be great if you could push a new release to rubygems.

**Comment by black-snow** [comment]
@seanabrahams good to know, thanks.

**Comment by bigtunacan** [comment]
@seanabrahams I've published to rubygems.
