### ISSUE TITLE
:limit option does not seem to have any effect

### ISSUE THREAD

**Issue by abartov** [bigtunacan/rails-jquery-autocomplete#91]
Using this gem with Rails 4.x, I can't seem to get the default behavior for :limit to change.  No matter what I pass, I get 10 results out of many more.  A debugger shows the options hash at the get_autocomplete_limit method indeed does not include a :limit key.  Other params I pass are correctly present in the hash in that function.  I couldn't identify why that parameter does not make it into the hash.  Thoughts?

**Comment by bigtunacan** [comment]
If this is still an issue please provide which ORM you are using as well as a code snippet that replicates the issue.
