### ISSUE TITLE
Selecting suggestion from list does not trigger change event in IE/Edge

### ISSUE THREAD

**Issue by jasonperrone** [bigtunacan/rails-jquery-autocomplete#92]
Title says it all. Works fine in Chrome. In IE and Edge, selecting a value from the autocomplete suggested list does not trigger a change event, which I depend on.

**Comment by bigtunacan** [comment]
@jasonperrone If this is still an issue for you can you provide a gist or basic repo that reproduces this issue and I will reopen.
