### ISSUE TITLE
Is it possible to work with multiple models?

### ISSUE THREAD

**Issue by adolfopeccin** [bigtunacan/rails-jquery-autocomplete#96]
Hello,

I want use with taggable for Model Interests and Skills.

Is this possible to use for one autocomplete url for results of two models?

Thank you

**Comment by bigtunacan** [comment]
You can just create a custom `get_autocomplete_items` method and then concatenate multiple results.

    def get_autocomplete_items(parameters)
      result_set_1 = Interests.search do
        fulltext parameters[:term] do
          fields (:first_name)
          fields (:middle_name)
          fields (:last_name)
          fields (:interest)
        end
        order_by (:last_name)
        paginate page: 1, per_page: parameters[:options][:limit]+1
      end.results
  
      result_set_2 = Skills.search do
        fulltext parameters[:term] do
          fields (:first_name)
          fields (:middle_name)
          fields (:last_name)
          fields (:skill)
        end
        order_by (:last_name)
        paginate page: 1, per_page: parameters[:options][:limit]+1
      end.results
  
      result_set_count = result_set_1.count + result_set_2.count
      result_set = result_set_1 + result_set_2
    end

**Comment by oscarsidebo** [comment]
Where is this custom method suppose to go, in the controller?
